openapi: 3.0.1
info:
  contact:
    email: support@superlink.me
    name: API Support
    url: https://superlink.me/about#contact-us
  description: API for Superlink
  license:
    name: MIT
  termsOfService: https://assets.superlink.me/tos-v2.html
  title: Superlink
  version: v0.1.17
servers:
- url: https://api.superlink.me/
paths:
  /v1/access-token:
    delete:
      description: Deletes an access token
      operationId: delete-access-token
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/api.AccessTokenDeleteRequest'
        description: access token delete request
        required: true
      responses:
        "204":
          content: {}
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.BadRequestResponse'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.BadRequestResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Deletes an access token
      tags:
      - access-token
      x-codegen-request-body-name: request
    get:
      description: Lists access tokens
      operationId: list-access-tokens
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.AccessTokenResponse'
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Lists access tokens
      tags:
      - access-token
    post:
      description: Creates an admin token
      operationId: create-access-token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.AccessTokenCreateRequest'
        description: access token create request
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.AccessTokenResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.BadRequestResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Creates an admin token
      tags:
      - access-token
      x-codegen-request-body-name: request
  /v1/card-image/{domain}.svg:
    get:
      description: returns the image for a "domain" nft
      operationId: get-token-image-by-domain
      parameters:
      - description: firstname.lastname
        in: path
        name: domain
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            image/svg+xml:
              schema:
                type: string
          description: OK
        "404":
          content:
            image/svg+xml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Not Found
        "500":
          content:
            image/svg+xml:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      summary: Returns a SVG image for a Superlink NFT
      tags:
      - nft
  /v1/health:
    get:
      description: Checks the health of the API
      operationId: health-check
      responses:
        "200":
          content: {}
          description: OK
        "500":
          content: {}
          description: Internal Server Error
      summary: Checks the health of the API
  /v1/metadata/{domain}:
    get:
      description: returns the metadata for a "domain" nft
      operationId: get-token-metadata-by-domain
      parameters:
      - description: firstname.lastname
        in: path
        name: domain
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.DomainMetadataResponse'
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      summary: Returns metadata usually associated with NFTs uri
      tags:
      - nft
  /v1/resolve/{domain}:
    get:
      description: resolve domain data by domain
      operationId: resolve-data-by-domain
      parameters:
      - description: firstname.lastname
        in: path
        name: domain
        required: true
        schema:
          type: string
      - description: "superlink,ens,ud"
        explode: false
        in: query
        name: nameservices
        schema:
          items:
            enum:
            - ud
            - ens
            - superlink
            type: string
          type: array
        style: form
      - description: "BTC,ETH,MATIC"
        explode: false
        in: query
        name: coins
        schema:
          items:
            enum:
            - BTC
            - LTC
            - DOGE
            - RDD
            - DASH
            - PPC
            - NMC
            - FTC
            - XCP
            - BLK
            - NSR
            - NBT
            - MZC
            - VIA
            - RBY
            - GRS
            - DGC
            - DGB
            - MONA
            - CLAM
            - XPM
            - NEOS
            - JBS
            - ZRC
            - VTC
            - NXT
            - BURST
            - MUE
            - ZOOM
            - SDC
            - PKB
            - PND
            - START
            - MOIN
            - EXP
            - DCR
            - XEM
            - PART
            - SHR
            - NVC
            - AC
            - BTCD
            - DOPE
            - TPC
            - AIB
            - EDRC
            - SYS
            - SLR
            - SMLY
            - ETH
            - PSB
            - XBC
            - NXS
            - INSN
            - OK
            - BRIT
            - CMP
            - CRW
            - BELA
            - ICX
            - FJC
            - MIX
            - CLUB
            - RICHX
            - POT
            - QRK
            - TRC
            - GRC
            - AUR
            - IXC
            - NLG
            - BITB
            - XMY
            - BSD
            - UNO
            - GB
            - SHM
            - CRX
            - BIQ
            - EVO
            - STO
            - BIGUP
            - GAME
            - DLC
            - ZYD
            - DBIC
            - STRAT
            - SH
            - MARS
            - UBQ
            - PTC
            - NRO
            - ARK
            - USC
            - THC
            - LINX
            - ECN
            - DNR
            - PINK
            - ATOM
            - PIVX
            - FLASH
            - ZEN
            - PUT
            - ZNY
            - UNIFY
            - XST
            - VC
            - XMR
            - VOX
            - NAV
            - ZEC
            - LSK
            - STEEM
            - XZC
            - RBTC
            - RPT
            - KMD
            - RIC
            - XRP
            - NEBL
            - ZCL
            - WHL
            - ERC
            - DMD
            - BTM
            - BIO
            - SSN
            - TOA
            - BTX
            - ACC
            - ELLA
            - PIRL
            - XNO
            - VIVO
            - FRST
            - HNC
            - BUZZ
            - MBRS
            - HC
            - HTML
            - ODN
            - ONX
            - RVN
            - GBX
            - BTCZ
            - POA
            - NYC
            - MXT
            - WC
            - MNX
            - MUSIC
            - CRAVE
            - STAK
            - LCH
            - EXCL
            - LCC
            - XFE
            - EOS
            - TRX
            - KOBO
            - HUSH
            - BAN
            - ETF
            - OMNI
            - BIFI
            - CNMC
            - BCN
            - RIN
            - ATP
            - EVT
            - ATN
            - BIS
            - NEET
            - BOPO
            - OOT
            - ALIAS
            - BOXY
            - FLO
            - MEC
            - BTDX
            - XAX
            - ANON
            - LTZ
            - SMART
            - XUEZ
            - HLM
            - WEB
            - ACM
            - BITC
            - TZC
            - VAR
            - IOV
            - FIO
            - BSV
            - DXN
            - PCX
            - LOKI
            - NIM
            - EXOS
            - ECA
            - SOOM
            - FREE
            - NPW
            - BST
            - ZEST
            - ABT
            - PION
            - ZBUX
            - KPL
            - TPAY
            - ZILLA
            - ANK
            - BCC
            - HPB
            - ONE
            - SBC
            - IPC
            - DMTC
            - OGC
            - SHIT
            - ANDES
            - AREPA
            - BOLI
            - RIL
            - BRAVO
            - ALGO
            - BZX
            - GXX
            - HEAT
            - XDN
            - FSN
            - BOLD
            - IOST
            - TKEY
            - USE
            - BCZ
            - IOC
            - ASF
            - MASS
            - FAIR
            - NUKO
            - CMT
            - EUNO
            - IOTX
            - ONION
            - BTS
            - UGAS
            - ADS
            - ARA
            - ZIL
            - MOAC
            - SWTC
            - VNSC
            - ECC
            - RPD
            - RAP
            - GARD
            - ZER
            - EBST
            - SHARD
            - CMM
            - BLOCK
            - AUDAX
            - LUNA
            - ZPM
            - MEM
            - SWIFT
            - FIX
            - CPC
            - VGO
            - DVT
            - MTNS
            - BLAST
            - DCT
            - AUX
            - USDP
            - HTDF
            - YEC
            - ARW
            - MDM
            - CYB
            - DOT
            - AEON
            - RES
            - AYA
            - DAPS
            - CSC
            - NOLLAR
            - XNOS
            - CPU
            - VCT
            - CZR
            - ABBC
            - HET
            - XAS
            - VDL
            - MED
            - ZVC
            - VESTX
            - DBT
            - SEOS
            - MXW
            - ZNZ
            - XCX
            - SOX
            - NYZO
            - ULC
            - KAL
            - XSN
            - DOGEC
            - QBC
            - IMG
            - QOS
            - PKT
            - LHD
            - CENNZ
            - UMBRU
            - EVER
            - XPC
            - NIX
            - UC
            - GALI
            - OLT
            - XBI
            - DONU
            - EARTHS
            - HDD
            - SUGAR
            - AILE
            - TENT
            - AIN
            - MSR
            - SUMO
            - ETN
            - BYTZ
            - WOW
            - XTNC
            - LTHN
            - NODE
            - AGM
            - TELOS
            - AION
            - KTV
            - ZCR
            - ERG
            - PESO
            - XRPHD
            - KSM
            - PCN
            - NCH
            - ICU
            - FNSA
            - AERGO
            - XTH
            - LV
            - PHR
            - VITAE
            - DIN
            - SPL
            - YCE
            - XLR
            - DGLD
            - XNS
            - EM
            - SHN
            - SEELE
            - AE
            - ODX
            - KAVA
            - GLEEC
            - FIL
            - RUTA
            - CSDT
            - ETI
            - ERE
            - BTH
            - MESG
            - FIMK
            - AR
            - OGO
            - RNG
            - PEXA
            - MOON
            - FCH
            - LAT
            - VEO
            - GFN
            - BAND
            - DROP
            - LYRA
            - CS
            - RUPX
            - THETA
            - SOL
            - THT
            - CFX
            - KUMA
            - HASH
            - CSPR
            - EARTH
            - EGLD
            - CHI
            - KOTO
            - XRD
            - AETH
            - DNA
            - SIERRA
            - LET
            - BTCV
            - ABA
            - SCC
            - EDG
            - AMS
            - BU
            - GRAM
            - YAP
            - NOVO
            - GHOST
            - HST
            - PRJ
            - YOU
            - BYND
            - FLOW
            - SCDO
            - BIND
            - COINEVO
            - SCRIBE
            - HYN
            - BHP
            - MKF
            - XDC
            - STR
            - HBC
            - KTS
            - LKR
            - XWC
            - DEAL
            - NTY
            - AG
            - CICO
            - IRIS
            - BDX
            - SLS
            - SRM
            - BPS
            - NKN
            - ICL
            - BONO
            - PLC
            - DUN
            - DMCH
            - CTC
            - GBCR
            - XDAG
            - SCAP
            - GTM
            - RNL
            - GRIN
            - MWC
            - DOCK
            - POLYX
            - DIVER
            - APN
            - MTC
            - NC
            - XINY
            - BUFS
            - STOS
            - TON
            - TAFT
            - HYDRA
            - NOR
            - WCN
            - PSWAP
            - XOR
            - SSP
            - DEI
            - ZERO
            - ALPHA
            - NOBL
            - EAST
            - KDA
            - SOUL
            - LORE
            - FNR
            - NEXUS
            - QTZ
            - XMA
            - CALL
            - VAL
            - EMIT
            - APTOS
            - ADON
            - BTSG
            - LFC
            - TREE
            - LX
            - XLN
            - ZRB
            - UCO
            - WMP
            - KOIN
            - PIRATE
            - ACT
            - PRKL
            - SSC
            - GC
            - PLGR
            - MPLGR
            - KNOX
            - ZED
            - CNDL
            - WLKRR
            - YUNGE
            - VOKEN
            - APL
            - EVRYNET
            - NENG
            - CHTA
            - OAS
            - KLV
            - VEIL
            - GTB
            - XDAI
            - COM
            - CHC
            - SERF
            - BNB
            - SIN
            - DLN
            - BONTE
            - PEER
            - ZET
            - ABY
            - XVC
            - MCX
            - HEALIOS
            - BMK
            - DENTX
            - CFG
            - XPRT
            - HONEY
            - BALLZ
            - COSA
            - BR
            - SUI
            - UIDD
            - ACA
            - BNC
            - TAU
            - PDEX
            - ZKS
            - QVT
            - MEER
            - REEF
            - CLO
            - BDB
            - ACE
            - CCN
            - BBA
            - CRUZ
            - SAPP
            - KYAN
            - AZR
            - CFL
            - TRTT
            - PNY
            - BECN
            - MONK
            - SAGA
            - SUV
            - ESK
            - BIR
            - MOBIC
            - FLS
            - DSM
            - HVH
            - MOB
            - IF
            - NAM
            - ZBC
            - NEO
            - TOMO
            - XSEL
            - LKSC
            - AS
            - XEC
            - LMO
            - HNT
            - FIS
            - SGE
            - GERT
            - META
            - FRA
            - CCD
            - GHM
            - LTP
            - VKAX
            - MATIC
            - UNW
            - TWINS
            - TLOS
            - AU
            - VCG
            - AIOZ
            - CORE
            - PEC
            - UNT
            - CAPS
            - SUM
            - TT
            - BKT
            - NODL
            - PCOIN
            - TAO
            - FTM
            - RPG
            - LAKE
            - ELV
            - BIC
            - EVC
            - ONT
            - CZZ
            - MCM
            - BTCR
            - RISE
            - DFI
            - EFI
            - ALPH
            - GLMR
            - MOVR
            - WPC
            - WEI
            - DFC
            - HYC
            - BEAM
            - ELF
            - AUDL
            - ATH
            - NEW
            - BTA
            - NEOX
            - MEWC
            - BCX
            - XTZ
            - BBP
            - ADA
            - TES
            - ZTX
            - CLC
            - VIPS
            - XMX
            - TRTL
            - EGEM
            - HODL
            - PHL
            - SC
            - MYT
            - POLIS
            - XMCC
            - COLX
            - GIN
            - MNP
            - MLN
            - KIN
            - EOSC
            - PKC
            - SKT
            - ANY
            - MCASH
            - "TRUE"
            - IOTE
            - BAY
            - XRG
            - CHZ
            - ASK
            - QTUM
            - ETP
            - GXC
            - CRP
            - ELA
            - SNOW
            - XIN
            - NEXI
            - AOA
            - NAS
            - BND
            - LUX
            - COS
            - CCC
            - SXP
            - ROI
            - DYN
            - SEQ
            - DEO
            - DST
            - CY
            - YEE
            - IOTA
            - SMR
            - AXE
            - XYM
            - XVM
            - FIC
            - HNS
            - ISK
            - ALTME
            - FUND
            - STX
            - SLU
            - COTI
            - ROGER
            - TOPL
            - KLY
            - SHFT
            - BTV
            - SKY
            - KLAY
            - BTQ
            - XCH
            - PLMNT
            - NULS
            - BBC
            - JGC
            - AVAX
            - BOBA
            - LOOP
            - STRK
            - NRG
            - FO
            - RTM
            - XRC
            - XPI
            - VARCH
            - TNKR
            - IPOS
            - MINA
            - BTY
            - SDGO
            - ARDR
            - MTR
            - SAFE
            - FLUX
            - RITO
            - XND
            - PAC
            - PWR
            - BELL
            - CHX
            - NEXA
            - BTT
            - FXTC
            - AMA
            - AXIV
            - EVE
            - STASH
            - CELO
            - TH
            - GRLC
            - GWL
            - ZYN
            - WICC
            - HOME
            - STC
            - STRAX
            - KAS
            - AKA
            - GENOM
            - ZAMA
            - SCR
            - VITE
            - WTC
            - ILT
            - XERO
            - LAX
            - BCO
            - BHD
            - PTN
            - VLX
            - WAN
            - WAVES
            - ABC
            - CRM
            - SEM
            - ION
            - FCT
            - WGR
            - OBSR
            - AFS
            - XDS
            - AQUA
            - HATCH
            - KUSD
            - GENS
            - EQ
            - QKC
            - FVDC
            - USDC
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ResolveDomainResponse'
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Resolves wallets and DNS records for a domain
      tags:
      - resolution
  /v1/reverse:
    delete:
      description: Assigns a reverse resolution address from a domain
      operationId: remove-reverse-resolution-address
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.ReverseResolutionDeleteRequest'
        description: reverse address delete request
        required: true
      responses:
        "204":
          content: {}
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.BadRequestResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Assigns a reverse resolution address from a domain
      tags:
      - resolution
      x-codegen-request-body-name: request
    post:
      description: Assigns an address to a domain for reverse resolution
      operationId: set-reverse-resolution-address
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.SetReverseAddressRequest'
        description: set reverse address request
        required: true
      responses:
        "204":
          content: {}
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.BadRequestResponse'
          description: Bad Request
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.BadRequestResponse'
          description: Conflict
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Assigns an address to a domain for reverse resolution
      tags:
      - resolution
      x-codegen-request-body-name: request
  /v1/reverse/{address}:
    get:
      description: resolve domain data by address
      operationId: resolve-data-by-address
      parameters:
      - description: superlink
        in: query
        name: nameservice
        schema:
          enum:
          - ud
          - ens
          - superlink
          type: string
      - description: 0x1234561234556
        in: path
        name: address
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ResolveDomainResponse'
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.InternalServerErrorResponse'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Resolves wallets and DNS records for an address
      tags:
      - resolution
components:
  schemas:
    api.AccessTokenCreateRequest:
      properties:
        label:
          example: company-xyz
          type: string
        type:
          allOf:
          - $ref: '#/components/schemas/data.AccessTokenType'
          example: CUSTOMER
          type: object
        validFrom:
          example: 2023-06-08T00:00:00Z
          type: string
        validTill:
          example: 2023-06-15T23:59:59Z
          type: string
      type: object
    api.AccessTokenDeleteRequest:
      properties:
        id:
          example: 248b8553-effa-4d99-a906-041a54f7df87
          type: string
      type: object
    api.AccessTokenResponse:
      example:
        createdAt: 2023-06-08T10:30:00Z
        validTill: 2023-06-15T23:59:59Z
        id: 248b8553-effa-4d99-a906-041a54f7df87
        label: company-xyz
        validFrom: 2023-06-08T00:00:00Z
        type: ADMIN
        value: <JWT>
        updatedAt: 2023-06-08T15:45:00Z
      properties:
        createdAt:
          example: 2023-06-08T10:30:00Z
          type: string
        id:
          example: 248b8553-effa-4d99-a906-041a54f7df87
          type: string
        label:
          example: company-xyz
          type: string
        type:
          enum:
          - ADMIN
          - CUSTOMER
          type: string
        updatedAt:
          example: 2023-06-08T15:45:00Z
          type: string
        validFrom:
          example: 2023-06-08T00:00:00Z
          type: string
        validTill:
          example: 2023-06-15T23:59:59Z
          type: string
        value:
          example: <JWT>
          type: string
      type: object
    api.BadRequestResponse:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/api.ErrorResponse'
          type: array
      type: object
    api.Coin:
      enum:
      - BTC
      - LTC
      - DOGE
      - RDD
      - DASH
      - PPC
      - NMC
      - FTC
      - XCP
      - BLK
      - NSR
      - NBT
      - MZC
      - VIA
      - RBY
      - GRS
      - DGC
      - DGB
      - MONA
      - CLAM
      - XPM
      - NEOS
      - JBS
      - ZRC
      - VTC
      - NXT
      - BURST
      - MUE
      - ZOOM
      - SDC
      - PKB
      - PND
      - START
      - MOIN
      - EXP
      - DCR
      - XEM
      - PART
      - SHR
      - NVC
      - AC
      - BTCD
      - DOPE
      - TPC
      - AIB
      - EDRC
      - SYS
      - SLR
      - SMLY
      - ETH
      - PSB
      - XBC
      - NXS
      - INSN
      - OK
      - BRIT
      - CMP
      - CRW
      - BELA
      - ICX
      - FJC
      - MIX
      - CLUB
      - RICHX
      - POT
      - QRK
      - TRC
      - GRC
      - AUR
      - IXC
      - NLG
      - BITB
      - XMY
      - BSD
      - UNO
      - GB
      - SHM
      - CRX
      - BIQ
      - EVO
      - STO
      - BIGUP
      - GAME
      - DLC
      - ZYD
      - DBIC
      - STRAT
      - SH
      - MARS
      - UBQ
      - PTC
      - NRO
      - ARK
      - USC
      - THC
      - LINX
      - ECN
      - DNR
      - PINK
      - ATOM
      - PIVX
      - FLASH
      - ZEN
      - PUT
      - ZNY
      - UNIFY
      - XST
      - VC
      - XMR
      - VOX
      - NAV
      - ZEC
      - LSK
      - STEEM
      - XZC
      - RBTC
      - RPT
      - KMD
      - RIC
      - XRP
      - NEBL
      - ZCL
      - WHL
      - ERC
      - DMD
      - BTM
      - BIO
      - SSN
      - TOA
      - BTX
      - ACC
      - ELLA
      - PIRL
      - XNO
      - VIVO
      - FRST
      - HNC
      - BUZZ
      - MBRS
      - HC
      - HTML
      - ODN
      - ONX
      - RVN
      - GBX
      - BTCZ
      - POA
      - NYC
      - MXT
      - WC
      - MNX
      - MUSIC
      - CRAVE
      - STAK
      - LCH
      - EXCL
      - LCC
      - XFE
      - EOS
      - TRX
      - KOBO
      - HUSH
      - BAN
      - ETF
      - OMNI
      - BIFI
      - CNMC
      - BCN
      - RIN
      - ATP
      - EVT
      - ATN
      - BIS
      - NEET
      - BOPO
      - OOT
      - ALIAS
      - BOXY
      - FLO
      - MEC
      - BTDX
      - XAX
      - ANON
      - LTZ
      - SMART
      - XUEZ
      - HLM
      - WEB
      - ACM
      - BITC
      - TZC
      - VAR
      - IOV
      - FIO
      - BSV
      - DXN
      - PCX
      - LOKI
      - NIM
      - EXOS
      - ECA
      - SOOM
      - FREE
      - NPW
      - BST
      - ZEST
      - ABT
      - PION
      - ZBUX
      - KPL
      - TPAY
      - ZILLA
      - ANK
      - BCC
      - HPB
      - ONE
      - SBC
      - IPC
      - DMTC
      - OGC
      - SHIT
      - ANDES
      - AREPA
      - BOLI
      - RIL
      - BRAVO
      - ALGO
      - BZX
      - GXX
      - HEAT
      - XDN
      - FSN
      - BOLD
      - IOST
      - TKEY
      - USE
      - BCZ
      - IOC
      - ASF
      - MASS
      - FAIR
      - NUKO
      - CMT
      - EUNO
      - IOTX
      - ONION
      - BTS
      - UGAS
      - ADS
      - ARA
      - ZIL
      - MOAC
      - SWTC
      - VNSC
      - ECC
      - RPD
      - RAP
      - GARD
      - ZER
      - EBST
      - SHARD
      - CMM
      - BLOCK
      - AUDAX
      - LUNA
      - ZPM
      - MEM
      - SWIFT
      - FIX
      - CPC
      - VGO
      - DVT
      - MTNS
      - BLAST
      - DCT
      - AUX
      - USDP
      - HTDF
      - YEC
      - ARW
      - MDM
      - CYB
      - DOT
      - AEON
      - RES
      - AYA
      - DAPS
      - CSC
      - NOLLAR
      - XNOS
      - CPU
      - VCT
      - CZR
      - ABBC
      - HET
      - XAS
      - VDL
      - MED
      - ZVC
      - VESTX
      - DBT
      - SEOS
      - MXW
      - ZNZ
      - XCX
      - SOX
      - NYZO
      - ULC
      - KAL
      - XSN
      - DOGEC
      - QBC
      - IMG
      - QOS
      - PKT
      - LHD
      - CENNZ
      - UMBRU
      - EVER
      - XPC
      - NIX
      - UC
      - GALI
      - OLT
      - XBI
      - DONU
      - EARTHS
      - HDD
      - SUGAR
      - AILE
      - TENT
      - AIN
      - MSR
      - SUMO
      - ETN
      - BYTZ
      - WOW
      - XTNC
      - LTHN
      - NODE
      - AGM
      - TELOS
      - AION
      - KTV
      - ZCR
      - ERG
      - PESO
      - XRPHD
      - KSM
      - PCN
      - NCH
      - ICU
      - FNSA
      - AERGO
      - XTH
      - LV
      - PHR
      - VITAE
      - DIN
      - SPL
      - YCE
      - XLR
      - DGLD
      - XNS
      - EM
      - SHN
      - SEELE
      - AE
      - ODX
      - KAVA
      - GLEEC
      - FIL
      - RUTA
      - CSDT
      - ETI
      - ERE
      - BTH
      - MESG
      - FIMK
      - AR
      - OGO
      - RNG
      - PEXA
      - MOON
      - FCH
      - LAT
      - VEO
      - GFN
      - BAND
      - DROP
      - LYRA
      - CS
      - RUPX
      - THETA
      - SOL
      - THT
      - CFX
      - KUMA
      - HASH
      - CSPR
      - EARTH
      - EGLD
      - CHI
      - KOTO
      - XRD
      - AETH
      - DNA
      - SIERRA
      - LET
      - BTCV
      - ABA
      - SCC
      - EDG
      - AMS
      - BU
      - GRAM
      - YAP
      - NOVO
      - GHOST
      - HST
      - PRJ
      - YOU
      - BYND
      - FLOW
      - SCDO
      - BIND
      - COINEVO
      - SCRIBE
      - HYN
      - BHP
      - MKF
      - XDC
      - STR
      - HBC
      - KTS
      - LKR
      - XWC
      - DEAL
      - NTY
      - AG
      - CICO
      - IRIS
      - BDX
      - SLS
      - SRM
      - BPS
      - NKN
      - ICL
      - BONO
      - PLC
      - DUN
      - DMCH
      - CTC
      - GBCR
      - XDAG
      - SCAP
      - GTM
      - RNL
      - GRIN
      - MWC
      - DOCK
      - POLYX
      - DIVER
      - APN
      - MTC
      - NC
      - XINY
      - BUFS
      - STOS
      - TON
      - TAFT
      - HYDRA
      - NOR
      - WCN
      - PSWAP
      - XOR
      - SSP
      - DEI
      - ZERO
      - ALPHA
      - NOBL
      - EAST
      - KDA
      - SOUL
      - LORE
      - FNR
      - NEXUS
      - QTZ
      - XMA
      - CALL
      - VAL
      - EMIT
      - APTOS
      - ADON
      - BTSG
      - LFC
      - TREE
      - LX
      - XLN
      - ZRB
      - UCO
      - WMP
      - KOIN
      - PIRATE
      - ACT
      - PRKL
      - SSC
      - GC
      - PLGR
      - MPLGR
      - KNOX
      - ZED
      - CNDL
      - WLKRR
      - YUNGE
      - VOKEN
      - APL
      - EVRYNET
      - NENG
      - CHTA
      - OAS
      - KLV
      - VEIL
      - GTB
      - XDAI
      - COM
      - CHC
      - SERF
      - BNB
      - SIN
      - DLN
      - BONTE
      - PEER
      - ZET
      - ABY
      - XVC
      - MCX
      - HEALIOS
      - BMK
      - DENTX
      - CFG
      - XPRT
      - HONEY
      - BALLZ
      - COSA
      - BR
      - SUI
      - UIDD
      - ACA
      - BNC
      - TAU
      - PDEX
      - ZKS
      - QVT
      - MEER
      - REEF
      - CLO
      - BDB
      - ACE
      - CCN
      - BBA
      - CRUZ
      - SAPP
      - KYAN
      - AZR
      - CFL
      - TRTT
      - PNY
      - BECN
      - MONK
      - SAGA
      - SUV
      - ESK
      - BIR
      - MOBIC
      - FLS
      - DSM
      - HVH
      - MOB
      - IF
      - NAM
      - ZBC
      - NEO
      - TOMO
      - XSEL
      - LKSC
      - AS
      - XEC
      - LMO
      - HNT
      - FIS
      - SGE
      - GERT
      - META
      - FRA
      - CCD
      - GHM
      - LTP
      - VKAX
      - MATIC
      - UNW
      - TWINS
      - TLOS
      - AU
      - VCG
      - AIOZ
      - CORE
      - PEC
      - UNT
      - CAPS
      - SUM
      - TT
      - BKT
      - NODL
      - PCOIN
      - TAO
      - FTM
      - RPG
      - LAKE
      - ELV
      - BIC
      - EVC
      - ONT
      - CZZ
      - MCM
      - BTCR
      - RISE
      - DFI
      - EFI
      - ALPH
      - GLMR
      - MOVR
      - WPC
      - WEI
      - DFC
      - HYC
      - BEAM
      - ELF
      - AUDL
      - ATH
      - NEW
      - BTA
      - NEOX
      - MEWC
      - BCX
      - XTZ
      - BBP
      - ADA
      - TES
      - ZTX
      - CLC
      - VIPS
      - XMX
      - TRTL
      - EGEM
      - HODL
      - PHL
      - SC
      - MYT
      - POLIS
      - XMCC
      - COLX
      - GIN
      - MNP
      - MLN
      - KIN
      - EOSC
      - PKC
      - SKT
      - ANY
      - MCASH
      - "TRUE"
      - IOTE
      - BAY
      - XRG
      - CHZ
      - ASK
      - QTUM
      - ETP
      - GXC
      - CRP
      - ELA
      - SNOW
      - XIN
      - NEXI
      - AOA
      - NAS
      - BND
      - LUX
      - COS
      - CCC
      - SXP
      - ROI
      - DYN
      - SEQ
      - DEO
      - DST
      - CY
      - YEE
      - IOTA
      - SMR
      - AXE
      - XYM
      - XVM
      - FIC
      - HNS
      - ISK
      - ALTME
      - FUND
      - STX
      - SLU
      - COTI
      - ROGER
      - TOPL
      - KLY
      - SHFT
      - BTV
      - SKY
      - KLAY
      - BTQ
      - XCH
      - PLMNT
      - NULS
      - BBC
      - JGC
      - AVAX
      - BOBA
      - LOOP
      - STRK
      - NRG
      - FO
      - RTM
      - XRC
      - XPI
      - VARCH
      - TNKR
      - IPOS
      - MINA
      - BTY
      - SDGO
      - ARDR
      - MTR
      - SAFE
      - FLUX
      - RITO
      - XND
      - PAC
      - PWR
      - BELL
      - CHX
      - NEXA
      - BTT
      - FXTC
      - AMA
      - AXIV
      - EVE
      - STASH
      - CELO
      - TH
      - GRLC
      - GWL
      - ZYN
      - WICC
      - HOME
      - STC
      - STRAX
      - KAS
      - AKA
      - GENOM
      - ZAMA
      - SCR
      - VITE
      - WTC
      - ILT
      - XERO
      - LAX
      - BCO
      - BHD
      - PTN
      - VLX
      - WAN
      - WAVES
      - ABC
      - CRM
      - SEM
      - ION
      - FCT
      - WGR
      - OBSR
      - AFS
      - XDS
      - AQUA
      - HATCH
      - KUSD
      - GENS
      - EQ
      - QKC
      - FVDC
      - USDC
      type: string
      x-enum-varnames:
      - BTC
      - LTC
      - DOGE
      - RDD
      - DASH
      - PPC
      - NMC
      - FTC
      - XCP
      - BLK
      - NSR
      - NBT
      - MZC
      - VIA
      - RBY
      - GRS
      - DGC
      - DGB
      - MONA
      - CLAM
      - XPM
      - NEOS
      - JBS
      - ZRC
      - VTC
      - NXT
      - BURST
      - MUE
      - ZOOM
      - SDC
      - PKB
      - PND
      - START
      - MOIN
      - EXP
      - DCR
      - XEM
      - PART
      - SHR
      - NVC
      - AC
      - BTCD
      - DOPE
      - TPC
      - AIB
      - EDRC
      - SYS
      - SLR
      - SMLY
      - ETH
      - PSB
      - XBC
      - NXS
      - INSN
      - OK
      - BRIT
      - CMP
      - CRW
      - BELA
      - ICX
      - FJC
      - MIX
      - CLUB
      - RICHX
      - POT
      - QRK
      - TRC
      - GRC
      - AUR
      - IXC
      - NLG
      - BITB
      - XMY
      - BSD
      - UNO
      - GB
      - SHM
      - CRX
      - BIQ
      - EVO
      - STO
      - BIGUP
      - GAME
      - DLC
      - ZYD
      - DBIC
      - STRAT
      - SH
      - MARS
      - UBQ
      - PTC
      - NRO
      - ARK
      - USC
      - THC
      - LINX
      - ECN
      - DNR
      - PINK
      - ATOM
      - PIVX
      - FLASH
      - ZEN
      - PUT
      - ZNY
      - UNIFY
      - XST
      - VC
      - XMR
      - VOX
      - NAV
      - ZEC
      - LSK
      - STEEM
      - XZC
      - RBTC
      - RPT
      - KMD
      - RIC
      - XRP
      - NEBL
      - ZCL
      - WHL
      - ERC
      - DMD
      - BTM
      - BIO
      - SSN
      - TOA
      - BTX
      - ACC
      - ELLA
      - PIRL
      - XNO
      - VIVO
      - FRST
      - HNC
      - BUZZ
      - MBRS
      - HC
      - HTML
      - ODN
      - ONX
      - RVN
      - GBX
      - BTCZ
      - POA
      - NYC
      - MXT
      - WC
      - MNX
      - MUSIC
      - CRAVE
      - STAK
      - LCH
      - EXCL
      - LCC
      - XFE
      - EOS
      - TRX
      - KOBO
      - HUSH
      - BAN
      - ETF
      - OMNI
      - BIFI
      - CNMC
      - BCN
      - RIN
      - ATP
      - EVT
      - ATN
      - BIS
      - NEET
      - BOPO
      - OOT
      - ALIAS
      - BOXY
      - FLO
      - MEC
      - BTDX
      - XAX
      - ANON
      - LTZ
      - SMART
      - XUEZ
      - HLM
      - WEB
      - ACM
      - BITC
      - TZC
      - VAR
      - IOV
      - FIO
      - BSV
      - DXN
      - PCX
      - LOKI
      - NIM
      - EXOS
      - ECA
      - SOOM
      - FREE
      - NPW
      - BST
      - ZEST
      - ABT
      - PION
      - ZBUX
      - KPL
      - TPAY
      - ZILLA
      - ANK
      - BCC
      - HPB
      - ONE
      - SBC
      - IPC
      - DMTC
      - OGC
      - SHIT
      - ANDES
      - AREPA
      - BOLI
      - RIL
      - BRAVO
      - ALGO
      - BZX
      - GXX
      - HEAT
      - XDN
      - FSN
      - BOLD
      - IOST
      - TKEY
      - USE
      - BCZ
      - IOC
      - ASF
      - MASS
      - FAIR
      - NUKO
      - CMT
      - EUNO
      - IOTX
      - ONION
      - BTS
      - UGAS
      - ADS
      - ARA
      - ZIL
      - MOAC
      - SWTC
      - VNSC
      - ECC
      - RPD
      - RAP
      - GARD
      - ZER
      - EBST
      - SHARD
      - CMM
      - BLOCK
      - AUDAX
      - LUNA
      - ZPM
      - MEM
      - SWIFT
      - FIX
      - CPC
      - VGO
      - DVT
      - MTNS
      - BLAST
      - DCT
      - AUX
      - USDP
      - HTDF
      - YEC
      - ARW
      - MDM
      - CYB
      - DOT
      - AEON
      - RES
      - AYA
      - DAPS
      - CSC
      - NOLLAR
      - XNOS
      - CPU
      - VCT
      - CZR
      - ABBC
      - HET
      - XAS
      - VDL
      - MED
      - ZVC
      - VESTX
      - DBT
      - SEOS
      - MXW
      - ZNZ
      - XCX
      - SOX
      - NYZO
      - ULC
      - KAL
      - XSN
      - DOGEC
      - QBC
      - IMG
      - QOS
      - PKT
      - LHD
      - CENNZ
      - UMBRU
      - EVER
      - XPC
      - NIX
      - UC
      - GALI
      - OLT
      - XBI
      - DONU
      - EARTHS
      - HDD
      - SUGAR
      - AILE
      - TENT
      - AIN
      - MSR
      - SUMO
      - ETN
      - BYTZ
      - WOW
      - XTNC
      - LTHN
      - NODE
      - AGM
      - TELOS
      - AION
      - KTV
      - ZCR
      - ERG
      - PESO
      - XRPHD
      - KSM
      - PCN
      - NCH
      - ICU
      - FNSA
      - AERGO
      - XTH
      - LV
      - PHR
      - VITAE
      - DIN
      - SPL
      - YCE
      - XLR
      - DGLD
      - XNS
      - EM
      - SHN
      - SEELE
      - AE
      - ODX
      - KAVA
      - GLEEC
      - FIL
      - RUTA
      - CSDT
      - ETI
      - ERE
      - BTH
      - MESG
      - FIMK
      - AR
      - OGO
      - RNG
      - PEXA
      - MOON
      - FCH
      - LAT
      - VEO
      - GFN
      - BAND
      - DROP
      - LYRA
      - CS
      - RUPX
      - THETA
      - SOL
      - THT
      - CFX
      - KUMA
      - HASH
      - CSPR
      - EARTH
      - EGLD
      - CHI
      - KOTO
      - XRD
      - AETH
      - DNA
      - SIERRA
      - LET
      - BTCV
      - ABA
      - SCC
      - EDG
      - AMS
      - BU
      - GRAM
      - YAP
      - NOVO
      - GHOST
      - HST
      - PRJ
      - YOU
      - BYND
      - FLOW
      - SCDO
      - BIND
      - COINEVO
      - SCRIBE
      - HYN
      - BHP
      - MKF
      - XDC
      - STR
      - HBC
      - KTS
      - LKR
      - XWC
      - DEAL
      - NTY
      - AG
      - CICO
      - IRIS
      - BDX
      - SLS
      - SRM
      - BPS
      - NKN
      - ICL
      - BONO
      - PLC
      - DUN
      - DMCH
      - CTC
      - GBCR
      - XDAG
      - SCAP
      - GTM
      - RNL
      - GRIN
      - MWC
      - DOCK
      - POLYX
      - DIVER
      - APN
      - MTC
      - NC
      - XINY
      - BUFS
      - STOS
      - TON
      - TAFT
      - HYDRA
      - NOR
      - WCN
      - PSWAP
      - XOR
      - SSP
      - DEI
      - ZERO
      - ALPHA
      - NOBL
      - EAST
      - KDA
      - SOUL
      - LORE
      - FNR
      - NEXUS
      - QTZ
      - XMA
      - CALL
      - VAL
      - EMIT
      - APTOS
      - ADON
      - BTSG
      - LFC
      - TREE
      - LX
      - XLN
      - ZRB
      - UCO
      - WMP
      - KOIN
      - PIRATE
      - ACT
      - PRKL
      - SSC
      - GC
      - PLGR
      - MPLGR
      - KNOX
      - ZED
      - CNDL
      - WLKRR
      - YUNGE
      - VOKEN
      - APL
      - EVRYNET
      - NENG
      - CHTA
      - OAS
      - KLV
      - VEIL
      - GTB
      - XDAI
      - COM
      - CHC
      - SERF
      - BNB
      - SIN
      - DLN
      - BONTE
      - PEER
      - ZET
      - ABY
      - XVC
      - MCX
      - HEALIOS
      - BMK
      - DENTX
      - CFG
      - XPRT
      - HONEY
      - BALLZ
      - COSA
      - BR
      - SUI
      - UIDD
      - ACA
      - BNC
      - TAU
      - PDEX
      - ZKS
      - QVT
      - MEER
      - REEF
      - CLO
      - BDB
      - ACE
      - CCN
      - BBA
      - CRUZ
      - SAPP
      - KYAN
      - AZR
      - CFL
      - TRTT
      - PNY
      - BECN
      - MONK
      - SAGA
      - SUV
      - ESK
      - BIR
      - MOBIC
      - FLS
      - DSM
      - HVH
      - MOB
      - IF
      - NAM
      - ZBC
      - NEO
      - TOMO
      - XSEL
      - LKSC
      - AS
      - XEC
      - LMO
      - HNT
      - FIS
      - SGE
      - GERT
      - META
      - FRA
      - CCD
      - GHM
      - LTP
      - VKAX
      - MATIC
      - UNW
      - TWINS
      - TLOS
      - AU
      - VCG
      - AIOZ
      - CORE
      - PEC
      - UNT
      - CAPS
      - SUM
      - TT
      - BKT
      - NODL
      - PCOIN
      - TAO
      - FTM
      - RPG
      - LAKE
      - ELV
      - BIC
      - EVC
      - ONT
      - CZZ
      - MCM
      - BTCR
      - RISE
      - DFI
      - EFI
      - ALPH
      - GLMR
      - MOVR
      - WPC
      - WEI
      - DFC
      - HYC
      - BEAM
      - ELF
      - AUDL
      - ATH
      - NEW
      - BTA
      - NEOX
      - MEWC
      - BCX
      - XTZ
      - BBP
      - ADA
      - TES
      - ZTX
      - CLC
      - VIPS
      - XMX
      - TRTL
      - EGEM
      - HODL
      - PHL
      - SC
      - MYT
      - POLIS
      - XMCC
      - COLX
      - GIN
      - MNP
      - MLN
      - KIN
      - EOSC
      - PKC
      - SKT
      - ANY
      - MCASH
      - "TRUE"
      - IOTE
      - BAY
      - XRG
      - CHZ
      - ASK
      - QTUM
      - ETP
      - GXC
      - CRP
      - ELA
      - SNOW
      - XIN
      - NEXI
      - AOA
      - NAS
      - BND
      - LUX
      - COS
      - CCC
      - SXP
      - ROI
      - DYN
      - SEQ
      - DEO
      - DST
      - CY
      - YEE
      - IOTA
      - SMR
      - AXE
      - XYM
      - XVM
      - FIC
      - HNS
      - ISK
      - ALTME
      - FUND
      - STX
      - SLU
      - COTI
      - ROGER
      - TOPL
      - KLY
      - SHFT
      - BTV
      - SKY
      - KLAY
      - BTQ
      - XCH
      - PLMNT
      - NULS
      - BBC
      - JGC
      - AVAX
      - BOBA
      - LOOP
      - STRK
      - NRG
      - FO
      - RTM
      - XRC
      - XPI
      - VARCH
      - TNKR
      - IPOS
      - MINA
      - BTY
      - SDGO
      - ARDR
      - MTR
      - SAFE
      - FLUX
      - RITO
      - XND
      - PAC
      - PWR
      - BELL
      - CHX
      - NEXA
      - BTT
      - FXTC
      - AMA
      - AXIV
      - EVE
      - STASH
      - CELO
      - TH
      - GRLC
      - GWL
      - ZYN
      - WICC
      - HOME
      - STC
      - STRAX
      - KAS
      - AKA
      - GENOM
      - ZAMA
      - SCR
      - VITE
      - WTC
      - ILT
      - XERO
      - LAX
      - BCO
      - BHD
      - PTN
      - VLX
      - WAN
      - WAVES
      - ABC
      - CRM
      - SEM
      - ION
      - FCT
      - WGR
      - OBSR
      - AFS
      - XDS
      - AQUA
      - HATCH
      - KUSD
      - GENS
      - EQ
      - QKC
      - FVDC
      - USDC
    api.DNSRecord:
      example:
        name: firstname.lastname
        type: A
        ttl: 3600
        value: 192.168.0.1
      properties:
        name:
          example: firstname.lastname
          type: string
        ttl:
          example: 3600
          type: integer
        type:
          example: A
          type: string
        value:
          example: 192.168.0.1
          type: string
      type: object
    api.DomainMetadataResponse:
      example:
        image: https://api.superlink.me/card-image/jon.johnson.svg
        external_url: https://superlink.me/animation?name=jon.johnson
        namehash: 0x3538e2ebd840880e82448521324fc0c308fc6cd576a65a532a51c8d60c32b58a
        tokenId: "24073090563576551262032245933984978621011965102670616730489196997318148273546"
        image_url: https://api.superlink.me/card-image/jon.johnson.svg
        name: jon.johnson
        description: A blockchain domain. Use it to resolve your cryptocurrency addresses
          and decentralized websites.
        avatar: https://assets.superlink.me/avatar/b94c22d4-02b4-464e-aead-3f6cafceb1db
      properties:
        avatar:
          example: https://assets.superlink.me/avatar/b94c22d4-02b4-464e-aead-3f6cafceb1db
          type: string
        description:
          example: A blockchain domain. Use it to resolve your cryptocurrency addresses
            and decentralized websites.
          type: string
        external_url:
          example: https://superlink.me/animation?name=jon.johnson
          type: string
        image:
          example: https://api.superlink.me/card-image/jon.johnson.svg
          type: string
        image_url:
          example: https://api.superlink.me/card-image/jon.johnson.svg
          type: string
        name:
          example: jon.johnson
          type: string
        namehash:
          example: 0x3538e2ebd840880e82448521324fc0c308fc6cd576a65a532a51c8d60c32b58a
          type: string
        tokenId:
          example: "24073090563576551262032245933984978621011965102670616730489196997318148273546"
          type: string
      type: object
    api.ErrorResponse:
      properties:
        field:
          example: field
          type: string
        info:
          example: error message
          type: string
      type: object
    api.InternalServerErrorResponse:
      properties:
        message:
          example: Internal server error
          type: string
      type: object
    api.NameService:
      enum:
      - ud
      - ens
      - superlink
      type: string
      x-enum-varnames:
      - UD
      - ENS
      - SUPERLINK
    api.ResolveDomainResponse:
      example:
        txtRecords:
        - value: value
          key: key
        - value: value
          key: key
        nameService: null
        dnsRecords:
        - name: firstname.lastname
          type: A
          ttl: 3600
          value: 192.168.0.1
        - name: firstname.lastname
          type: A
          ttl: 3600
          value: 192.168.0.1
        domain: domain
        wallets:
        - address: <wallet address>
          version: ERC20
          coin: null
        - address: <wallet address>
          version: ERC20
          coin: null
        ownerAddress: ownerAddress
        contentHash: contentHash
      properties:
        contentHash:
          type: string
        dnsRecords:
          items:
            $ref: '#/components/schemas/api.DNSRecord'
          type: array
        domain:
          type: string
        nameService:
          $ref: '#/components/schemas/api.NameService'
        ownerAddress:
          type: string
        txtRecords:
          items:
            $ref: '#/components/schemas/api.TXTRecord'
          type: array
        wallets:
          items:
            $ref: '#/components/schemas/api.WalletData'
          type: array
      type: object
    api.ReverseResolutionDeleteRequest:
      properties:
        domain:
          example: firstname.lastname
          type: string
      type: object
    api.SetReverseAddressRequest:
      properties:
        address:
          example: 0x1234567890abcdef1234567890abcdef12345678
          type: string
        domain:
          example: firstname.lastname
          type: string
        signedMessage:
          example: 0x1234567890abcdef1234567890abcdef12345678
          type: string
        userId:
          example: 248b8553-effa-4d99-a906-041a54f7df87
          type: string
      type: object
    api.TXTRecord:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    api.WalletData:
      example:
        address: <wallet address>
        version: ERC20
        coin: null
      properties:
        address:
          example: <wallet address>
          type: string
        coin:
          $ref: '#/components/schemas/api.Coin'
        version:
          example: ERC20
          type: string
      type: object
    data.AccessTokenType:
      enum:
      - ADMIN
      - CUSTOMER
      type: string
      x-enum-varnames:
      - AccessTokenTypeAdmin
      - AccessTokenTypeCustomer
  securitySchemes:
    BearerAuth:
      description: Type "Bearer" followed by a space and the JWT token.
      in: header
      name: Authorization
      type: apiKey
x-original-swagger-version: "2.0"
